# Signup Page Google Elements
create_account = "xpath://span[normalize-space()='Create account']"
first_name_field = "id:firstName"
last_name_field = "id:lastName"
next_button = "id=collectNameNext"
gender_next_button = "id=birthdaygenderNext"
email_next_button = "id=next"
password_next_button = "id=createpasswordNext"
month_field = "id:month"
option_dropdown = "xpath://option[@value='2']"
day_field = "id:day"
year_field = "id:year"
gender_dropdown = "id:gender"
gender_option = "css:select[id='gender'] option[value='3']"
create_your_own = "id:selectionc2"
new_email_field = "css:input[name='Username']"
new_password_field = "css:input[name='Passwd']"
new_confirm_password_field = "css:input[name='PasswdAgain']"
